import * as React from "react";
import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { PageHero } from "@/components/site/PageHero";
import { facultyById, deptBySlug } from "@/lib/site-data";
import { Download, Mail, Phone, GraduationCap, BookOpen, Award, FileText } from "lucide-react";
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, CartesianGrid, AreaChart, Area } from "recharts";
import { toast } from "sonner";

export const Route = createFileRoute("/faculty/$id")({
  loader: ({ params }) => {
    const f = facultyById(params.id);
    if (!f) throw notFound();
    return { f, dept: deptBySlug(f.dept) };
  },
  head: ({ loaderData }) => ({
    meta: [
      { title: `${loaderData?.f.name ?? "Faculty"} — EWU` },
      { name: "description", content: loaderData?.f.bio ?? "EWU faculty profile" },
      { property: "og:title", content: `${loaderData?.f.name ?? "Faculty"} — EWU` },
      { property: "og:description", content: loaderData?.f.bio ?? "" },
    ],
  }),
  notFoundComponent: () => (
    <div className="grid min-h-[60dvh] place-items-center text-center">
      <div>
        <p className="font-serif text-3xl font-bold">Faculty not found</p>
        <Link to="/faculty" className="mt-4 inline-block text-primary hover:underline">Browse all faculty</Link>
      </div>
    </div>
  ),
  component: FacultyProfile,
});

function FacultyProfile() {
  const { f, dept } = Route.useLoaderData();

  const citeData = [
    { y: "2020", c: 95 },
    { y: "2021", c: 142 },
    { y: "2022", c: 198 },
    { y: "2023", c: 264 },
    { y: "2024", c: 312 },
    { y: "2025", c: 398 },
    { y: "2026", c: 431 },
  ];
  const pubData = [
    { y: "2020", n: 4 },
    { y: "2021", n: 6 },
    { y: "2022", n: 8 },
    { y: "2023", n: 9 },
    { y: "2024", n: 11 },
    { y: "2025", n: 12 },
    { y: "2026", n: 14 },
  ];

  function generateCV() {
    const html = `<!doctype html><html><head><meta charset='utf-8'><title>CV — ${f.name}</title>
<style>
body{font-family:Georgia,serif;max-width:780px;margin:40px auto;padding:24px;color:#222;line-height:1.5}
h1{color:#7a2424;margin:0 0 4px;font-size:32px}
h2{color:#7a2424;border-bottom:1px solid #ddd;padding-bottom:4px;margin-top:28px;font-size:16px;text-transform:uppercase;letter-spacing:1px}
.muted{color:#666;font-size:13px}
ul{padding-left:20px;margin:8px 0}
.stat{display:inline-block;margin-right:18px;font-weight:bold}
@media print{body{margin:20px}}
</style></head><body>
<h1>${f.name}</h1>
<p class="muted">${f.designation} · ${dept?.name ?? ""} · East West University</p>
<p class="muted">${f.bio}</p>

<h2>Education</h2>
<ul>${(f.education as string[]).map((e: string) => `<li>${e}</li>`).join("")}</ul>

<h2>Research Interests</h2>
<p>${f.interests.join(" · ")}</p>

<h2>Research Metrics</h2>
<p><span class="stat">Publications: ${f.papers}</span> <span class="stat">Citations: ${f.cites}</span> <span class="stat">h-index: ${f.h}</span></p>

<h2>Selected Publications</h2>
<ol>
<li>Author et al., "Recent work in ${f.interests[0]}", Journal of ${dept?.short ?? "Research"}, 2026.</li>
<li>Author et al., "Studies on ${f.interests[1] ?? "applied research"}", International Review, 2025.</li>
<li>Author et al., "Bangladesh case study in ${f.interests[0]}", National Conference, 2024.</li>
</ol>

<h2>Contact</h2>
<p>${f.id}@ewubd.edu · East West University, Aftabnagar, Dhaka.</p>

<p style="margin-top:40px;text-align:center;color:#999;font-size:11px">Generated by the EWU Faculty Portal · ${new Date().toLocaleDateString()}</p>
</body></html>`;
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${f.name.replace(/\s+/g, "_")}_CV.html`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("CV generated and downloaded.");
  }

  return (
    <div>
      <PageHero
        eyebrow={dept?.name ?? "Faculty"}
        title={f.name}
        subtitle={f.designation}
        crumbs={[{ to: "/", label: "Home" }, { to: "/faculty", label: "Faculty" }, { label: f.name }]}
      />

      <section className="mx-auto max-w-7xl px-6 py-12">
        <div className="grid gap-10 lg:grid-cols-[1fr_2fr]">
          <aside className="space-y-4">
            <div className="rounded-2xl border border-border bg-card p-6 text-center">
              <div className="mx-auto grid h-28 w-28 place-items-center rounded-full brand-gradient font-serif text-4xl font-bold text-primary-foreground shadow-brick">
                {f.name.split(" ").slice(-2).map((p: string) => p[0]).join("")}
              </div>
              <h2 className="mt-4 font-serif text-xl font-bold">{f.name}</h2>
              <p className="text-sm text-muted-foreground">{f.designation}</p>
              <p className="mt-1 text-xs text-primary">{dept?.name}</p>
              <div className="mt-5 space-y-2 text-left text-sm">
                <p className="flex items-center gap-2 text-foreground/85"><Mail className="h-4 w-4 text-primary" /> {f.id}@ewubd.edu</p>
                <p className="flex items-center gap-2 text-foreground/85"><Phone className="h-4 w-4 text-primary" /> +880 9666 775 ext.{Math.abs(f.id.length * 31) % 900 + 100}</p>
                <p className="flex items-center gap-2 text-foreground/85"><GraduationCap className="h-4 w-4 text-primary" /> Office hours: Sun, Tue 2–4 pm</p>
              </div>
              <button onClick={generateCV} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-md bg-primary py-2.5 text-sm font-semibold text-primary-foreground hover:bg-primary-deep">
                <Download className="h-4 w-4" /> Generate CV (HTML)
              </button>
              <button onClick={() => toast("PDF export uses the printable CV. Use your browser's Save as PDF.", { duration: 5000 })} className="mt-2 inline-flex w-full items-center justify-center gap-2 rounded-md border border-input bg-background py-2 text-sm font-medium hover:bg-accent">
                <FileText className="h-4 w-4" /> Download CV (PDF)
              </button>
            </div>

            <div className="rounded-2xl border border-border bg-card p-6">
              <h3 className="font-serif text-lg font-bold">Research interests</h3>
              <div className="mt-3 flex flex-wrap gap-1.5">
                {(f.interests as string[]).map((i: string) => (
                  <span key={i} className="rounded-full bg-primary-soft px-2.5 py-1 text-xs font-medium text-primary-deep">{i}</span>
                ))}
              </div>
            </div>
          </aside>

          <div className="space-y-6">
            <div className="rounded-2xl border border-border bg-card p-6">
              <h3 className="font-serif text-xl font-bold">About</h3>
              <p className="mt-2 text-foreground/85">{f.bio}</p>
            </div>

            <div className="rounded-2xl border border-border bg-card p-6">
              <h3 className="font-serif text-xl font-bold">Education</h3>
              <ul className="mt-3 space-y-2 text-sm text-foreground/85">
                {(f.education as string[]).map((e: string) => (
                  <li key={e} className="flex items-start gap-2"><Award className="mt-0.5 h-4 w-4 shrink-0 text-gold" /> {e}</li>
                ))}
              </ul>
            </div>

            <div className="grid gap-4 sm:grid-cols-3">
              {[
                { i: BookOpen, n: f.papers, l: "Publications" },
                { i: Award, n: f.cites.toLocaleString(), l: "Citations" },
                { i: GraduationCap, n: f.h, l: "h-index" },
              ].map((s) => (
                <div key={s.l} className="rounded-2xl border border-border bg-card p-5">
                  <s.i className="h-5 w-5 text-primary" />
                  <p className="mt-3 font-serif text-2xl font-bold">{s.n}</p>
                  <p className="text-xs uppercase tracking-wider text-muted-foreground">{s.l}</p>
                </div>
              ))}
            </div>

            <div className="rounded-2xl border border-border bg-card p-6">
              <h3 className="font-serif text-xl font-bold">Citations over time</h3>
              <div className="mt-4 h-60">
                <ResponsiveContainer>
                  <AreaChart data={citeData}>
                    <defs>
                      <linearGradient id="g1" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="0%" stopColor="var(--color-primary)" stopOpacity={0.6} />
                        <stop offset="100%" stopColor="var(--color-primary)" stopOpacity={0} />
                      </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="3 3" className="stroke-border" />
                    <XAxis dataKey="y" className="text-xs" />
                    <YAxis className="text-xs" />
                    <Tooltip contentStyle={{ background: "var(--color-popover)", border: "1px solid var(--color-border)", borderRadius: 8 }} />
                    <Area type="monotone" dataKey="c" stroke="var(--color-primary)" fill="url(#g1)" strokeWidth={2} />
                  </AreaChart>
                </ResponsiveContainer>
              </div>
            </div>

            <div className="rounded-2xl border border-border bg-card p-6">
              <h3 className="font-serif text-xl font-bold">Publications per year</h3>
              <div className="mt-4 h-52">
                <ResponsiveContainer>
                  <LineChart data={pubData}>
                    <CartesianGrid strokeDasharray="3 3" className="stroke-border" />
                    <XAxis dataKey="y" className="text-xs" />
                    <YAxis className="text-xs" />
                    <Tooltip contentStyle={{ background: "var(--color-popover)", border: "1px solid var(--color-border)", borderRadius: 8 }} />
                    <Line type="monotone" dataKey="n" stroke="var(--color-gold)" strokeWidth={3} dot={{ r: 4, fill: "var(--color-gold)" }} />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </div>

            <div className="rounded-2xl border border-border bg-card p-6">
              <h3 className="font-serif text-xl font-bold">Selected publications</h3>
              <ol className="mt-4 space-y-3 text-sm">
                {[
                  `"Recent advances in ${f.interests[0]}" — Journal of ${dept?.short}, 2026.`,
                  `"Studies on ${f.interests[1] ?? "applied research"}" — International Review, 2025.`,
                  `"Bangladesh case study in ${f.interests[0]}" — National Conference, 2024.`,
                  `"A primer on ${f.interests[0]}" — EWU Press, 2023.`,
                ].map((p, i) => (
                  <li key={i} className="flex gap-3 rounded-lg bg-muted/40 p-3">
                    <span className="font-serif font-bold text-primary">{i + 1}.</span>
                    <span className="text-foreground/85">{p}</span>
                  </li>
                ))}
              </ol>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
